[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps = 
	bblanchon/ArduinoJson @ ^6.21.3
	adafruit/Adafruit AHTX0 @ ^2.0.5
	adafruit/Adafruit BMP280 Library @ ^2.6.8